import {
  LandmarkIcon,
  LayoutDashboardIcon,
  SparklesIcon,
  UsersIcon,
} from "lucide-react";

export const GENERAL_ERROR_MESSAGE =
  "Something went wrong. Please try again or come back later.";
export const UNAUTHED_ERROR_MESSAGE = "Please sign in to continue.";
export const INVALID_DATA_ERROR_MESSAGE = "Invalid data. Please try again.";
export const NO_PERMISSION_DATA_MESSAGE =
  "You do not have permission to do this.";

export const SEARCH_OPTION_ICONS = {
  "layout-dashboard": LayoutDashboardIcon,
  "landmark-icon": LandmarkIcon,
  "users-icon": UsersIcon,
  "sparkles-icon": SparklesIcon,
};

export const CODE_EDITOR_THEME = {
  id: "github-dark",
  base: "vs-dark",
  inherit: true,
  rules: [
    { token: "", foreground: "c9d1d9", background: "0d1117" },
    { token: "comment", foreground: "8b949e", fontStyle: "italic" },
    { token: "string", foreground: "a5d6ff" },
    { token: "string.escape", foreground: "79c0ff" },
    { token: "regexp", foreground: "a5d6ff" },
    { token: "keyword", foreground: "ff7b72" },
    { token: "keyword.control", foreground: "ff7b72" },
    { token: "keyword.operator", foreground: "ff7b72" },
    { token: "operator", foreground: "ff7b72" },
    { token: "number", foreground: "79c0ff" },
    { token: "constant", foreground: "79c0ff" },
    { token: "constant.language", foreground: "79c0ff" },
    { token: "constant.numeric", foreground: "79c0ff" },
    { token: "type", foreground: "ffa657" },
    { token: "class", foreground: "ffa657" },
    { token: "interface", foreground: "ffa657" },
    { token: "enum", foreground: "ffa657" },
    { token: "struct", foreground: "ffa657" },
    { token: "typeParameter", foreground: "ffa657" },
    { token: "function", foreground: "d2a8ff" },
    { token: "method", foreground: "d2a8ff" },
    { token: "property", foreground: "79c0ff" },
    { token: "variable", foreground: "ffa657" },
    { token: "variable.predefined", foreground: "ff7b72" },
    { token: "parameter", foreground: "ffa657" },
    { token: "tag", foreground: "7ee787" },
    { token: "tag.id", foreground: "79c0ff" },
    { token: "tag.class", foreground: "79c0ff" },
    { token: "attribute.name", foreground: "d2a8ff" },
    { token: "attribute.value", foreground: "a5d6ff" },
    { token: "delimiter", foreground: "c9d1d9" },
    { token: "delimiter.bracket", foreground: "c9d1d9" },
    { token: "delimiter.parenthesis", foreground: "c9d1d9" },
    { token: "invalid", foreground: "ffdcd7", background: "8e1519" },
  ],
  colors: {
    "editor.background": "#0d1117",
    "editor.foreground": "#c9d1d9",
    "editorLineNumber.foreground": "#6e7681",
    "editorLineNumber.activeForeground": "#f0f6fc",
    "editorCursor.foreground": "#58a6ff",
    "editor.selectionBackground": "#1f6feb66",
    "editor.selectionHighlightBackground": "#3fb95033",
    "editor.inactiveSelectionBackground": "#1f6feb33",
    "editor.wordHighlightBackground": "#6e768133",
    "editor.wordHighlightStrongBackground": "#6e76814d",
    "editor.findMatchBackground": "#9e6a03",
    "editor.findMatchHighlightBackground": "#9e6a0366",
    "editor.findRangeHighlightBackground": "#9e6a0333",
    "editor.lineHighlightBackground": "#161b22",
    "editor.lineHighlightBorder": "#30363d",
    "editorWhitespace.foreground": "#484f58",
    "editorIndentGuide.background1": "#21262d",
    "editorIndentGuide.activeBackground1": "#30363d",
    "editorBracketMatch.background": "#3fb9501a",
    "editorBracketMatch.border": "#3fb950",
    "editorBracketHighlight.foreground1": "#79c0ff",
    "editorBracketHighlight.foreground2": "#ffa657",
    "editorBracketHighlight.foreground3": "#d2a8ff",
    "editorBracketHighlight.foreground4": "#7ee787",
    "editorBracketHighlight.foreground5": "#ff7b72",
    "editorBracketHighlight.foreground6": "#a5d6ff",
    "editorGutter.background": "#0d1117",
    "editorGutter.modifiedBackground": "#d29922",
    "editorGutter.addedBackground": "#3fb950",
    "editorGutter.deletedBackground": "#f85149",
    "editorOverviewRuler.border": "#0d1117",
    "editorOverviewRuler.findMatchForeground": "#d29922",
    "editorOverviewRuler.errorForeground": "#f85149",
    "editorOverviewRuler.warningForeground": "#d29922",
    "editorOverviewRuler.infoForeground": "#58a6ff",
    "editorError.foreground": "#f85149",
    "editorWarning.foreground": "#d29922",
    "editorInfo.foreground": "#58a6ff",
    "editorHint.foreground": "#8b949e",
    "editorWidget.background": "#161b22",
    "editorWidget.foreground": "#c9d1d9",
    "editorWidget.border": "#30363d",
    "editorSuggestWidget.background": "#161b22",
    "editorSuggestWidget.foreground": "#c9d1d9",
    "editorSuggestWidget.border": "#30363d",
    "editorSuggestWidget.highlightForeground": "#58a6ff",
    "editorSuggestWidget.selectedBackground": "#1f6feb33",
    "editorHoverWidget.background": "#161b22",
    "editorHoverWidget.foreground": "#c9d1d9",
    "editorHoverWidget.border": "#30363d",
    "peekView.border": "#30363d",
    "peekViewEditor.background": "#0d1117",
    "peekViewResult.background": "#161b22",
    "peekViewResult.selectionBackground": "#1f6feb33",
    "peekViewTitle.background": "#161b22",
    "scrollbar.shadow": "#00000000",
    "scrollbarSlider.background": "#6e768166",
    "scrollbarSlider.hoverBackground": "#8b949e66",
    "scrollbarSlider.activeBackground": "#8b949e99",
  },
};
