import {
  LandmarkIcon,
  LayoutDashboardIcon,
  SparklesIcon,
  UsersIcon,
} from "lucide-react";

export const GENERAL_ERROR_MESSAGE =
  "Something went wrong. Please try again or come back later.";
export const UNAUTHED_ERROR_MESSAGE = "Please sign in to continue.";
export const INVALID_DATA_ERROR_MESSAGE = "Invalid data. Please try again.";
export const NO_PERMISSION_DATA_MESSAGE =
  "You do not have permission to do this.";
export const NOT_FOUND_ERROR_MESSAGE = "Resource not found.";

export const DEFAULT_PAGE = 1;
export const PAGE_SIZE = 20;

export const SEARCH_OPTION_ICONS = {
  "layout-dashboard": LayoutDashboardIcon,
  "landmark-icon": LandmarkIcon,
  "users-icon": UsersIcon,
  "sparkles-icon": SparklesIcon,
};

export const CODE_EDITOR_DARK_THEME = {
  id: "github-dark",
  base: "vs-dark",
  inherit: true,
  rules: [
    { token: "", foreground: "d6dee6", background: "0d1117" },
    { token: "comment", foreground: "8b949e", fontStyle: "italic" },
    { token: "string", foreground: "a5d6ff" },
    { token: "string.escape", foreground: "6cb6ff" },
    { token: "regexp", foreground: "a5d6ff" },
    { token: "keyword", foreground: "ff7b8a" },
    { token: "keyword.control", foreground: "ff7b8a" },
    { token: "keyword.operator", foreground: "ff7b8a" },
    { token: "operator", foreground: "ff7b8a" },
    { token: "number", foreground: "6cb6ff" },
    { token: "constant", foreground: "6cb6ff" },
    { token: "constant.language", foreground: "6cb6ff" },
    { token: "constant.numeric", foreground: "6cb6ff" },
    { token: "type", foreground: "c69cff" },
    { token: "class", foreground: "c69cff" },
    { token: "interface", foreground: "c69cff" },
    { token: "enum", foreground: "c69cff" },
    { token: "struct", foreground: "c69cff" },
    { token: "typeParameter", foreground: "c69cff" },
    { token: "function", foreground: "c69cff" },
    { token: "method", foreground: "c69cff" },
    { token: "property", foreground: "ffa657" },
    { token: "variable", foreground: "6cb6ff" },
    { token: "variable.predefined", foreground: "ff7b8a" },
    { token: "parameter", foreground: "ffa657" },
    { token: "tag", foreground: "7ee787" },
    { token: "tag.id", foreground: "6cb6ff" },
    { token: "tag.class", foreground: "6cb6ff" },
    { token: "attribute.name", foreground: "c69cff" },
    { token: "attribute.value", foreground: "a5d6ff" },
    { token: "delimiter", foreground: "d6dee6" },
    { token: "delimiter.bracket", foreground: "d6dee6" },
    { token: "delimiter.parenthesis", foreground: "d6dee6" },
    { token: "invalid", foreground: "ffdcd7", background: "8e1519" },
  ],
  colors: {
    "editor.background": "#0d1117",
    "editor.foreground": "#d6dee6",
    "editorLineNumber.foreground": "#768390",
    "editorLineNumber.activeForeground": "#f0f6fc",
    "editorCursor.foreground": "#6cb6ff",
    "editor.selectionBackground": "#3b6ea866",
    "editor.selectionHighlightBackground": "#76839033",
    "editor.inactiveSelectionBackground": "#3b6ea833",
    "editor.wordHighlightBackground": "#76839033",
    "editor.wordHighlightStrongBackground": "#7683904d",
    "editor.findMatchBackground": "#c6902666",
    "editor.findMatchHighlightBackground": "#c690263d",
    "editor.findRangeHighlightBackground": "#c6902626",
    "editor.lineHighlightBackground": "#161b22",
    "editor.lineHighlightBorder": "#30363d",
    "editorWhitespace.foreground": "#484f58",
    "editorIndentGuide.background1": "#21262d",
    "editorIndentGuide.activeBackground1": "#30363d",
    "editorBracketMatch.background": "#3fb9501a",
    "editorBracketMatch.border": "#3fb950",
    "editorBracketHighlight.foreground1": "#6cb6ff",
    "editorBracketHighlight.foreground2": "#ffa657",
    "editorBracketHighlight.foreground3": "#c69cff",
    "editorBracketHighlight.foreground4": "#7ee787",
    "editorBracketHighlight.foreground5": "#ff7b8a",
    "editorBracketHighlight.foreground6": "#a5d6ff",
    "editorGutter.background": "#0d1117",
    "editorGutter.modifiedBackground": "#c69026",
    "editorGutter.addedBackground": "#3fb950",
    "editorGutter.deletedBackground": "#f85149",
    "editorOverviewRuler.border": "#0d1117",
    "editorOverviewRuler.findMatchForeground": "#c69026",
    "editorOverviewRuler.errorForeground": "#f85149",
    "editorOverviewRuler.warningForeground": "#c69026",
    "editorOverviewRuler.infoForeground": "#6cb6ff",
    "editorError.foreground": "#f85149",
    "editorWarning.foreground": "#c69026",
    "editorInfo.foreground": "#6cb6ff",
    "editorHint.foreground": "#8b949e",
    "editorWidget.background": "#161b22",
    "editorWidget.foreground": "#d6dee6",
    "editorWidget.border": "#30363d",
    "editorSuggestWidget.background": "#161b22",
    "editorSuggestWidget.foreground": "#d6dee6",
    "editorSuggestWidget.border": "#30363d",
    "editorSuggestWidget.highlightForeground": "#6cb6ff",
    "editorSuggestWidget.selectedBackground": "#3b6ea833",
    "editorHoverWidget.background": "#161b22",
    "editorHoverWidget.foreground": "#d6dee6",
    "editorHoverWidget.border": "#30363d",
    "peekView.border": "#30363d",
    "peekViewEditor.background": "#0d1117",
    "peekViewResult.background": "#161b22",
    "peekViewResult.selectionBackground": "#3b6ea833",
    "peekViewTitle.background": "#161b22",
    "scrollbar.shadow": "#00000000",
    "scrollbarSlider.background": "#76839066",
    "scrollbarSlider.hoverBackground": "#8b949e66",
    "scrollbarSlider.activeBackground": "#8b949e99",
  },
};

export const CODE_EDITOR_LIGHT_THEME = {
  id: "github-light",
  base: "vs",
  inherit: true,
  rules: [
    { token: "", foreground: "1f2328", background: "ffffff" },
    { token: "comment", foreground: "57606a", fontStyle: "italic" },
    { token: "string", foreground: "0a3069" },
    { token: "string.escape", foreground: "116329" },
    { token: "regexp", foreground: "116329" },
    { token: "keyword", foreground: "cf222e" },
    { token: "keyword.control", foreground: "cf222e" },
    { token: "keyword.operator", foreground: "cf222e" },
    { token: "operator", foreground: "cf222e" },
    { token: "number", foreground: "0550ae" },
    { token: "constant", foreground: "0550ae" },
    { token: "constant.language", foreground: "0550ae" },
    { token: "constant.numeric", foreground: "0550ae" },
    { token: "type", foreground: "6639ba" },
    { token: "class", foreground: "6639ba" },
    { token: "interface", foreground: "6639ba" },
    { token: "enum", foreground: "6639ba" },
    { token: "struct", foreground: "6639ba" },
    { token: "typeParameter", foreground: "6639ba" },
    { token: "function", foreground: "6639ba" },
    { token: "method", foreground: "6639ba" },
    { token: "property", foreground: "0550ae" },
    { token: "variable", foreground: "953800" },
    { token: "variable.predefined", foreground: "cf222e" },
    { token: "parameter", foreground: "953800" },
    { token: "tag", foreground: "116329" },
    { token: "tag.id", foreground: "0550ae" },
    { token: "tag.class", foreground: "0550ae" },
    { token: "attribute.name", foreground: "6639ba" },
    { token: "attribute.value", foreground: "0a3069" },
    { token: "delimiter", foreground: "24292f" },
    { token: "delimiter.bracket", foreground: "57606a" },
    { token: "delimiter.parenthesis", foreground: "57606a" },
    { token: "invalid", foreground: "f6f8fa", background: "82071e" },
  ],
  colors: {
    "editor.background": "#ffffff",
    "editor.foreground": "#1f2328",
    "editorLineNumber.foreground": "#656d76",
    "editorLineNumber.activeForeground": "#24292f",
    "editorCursor.foreground": "#1f2328",
    "editor.selectionBackground": "#54aeff66",
    "editor.selectionHighlightBackground": "#afb8c133",
    "editor.inactiveSelectionBackground": "#54aeff33",
    "editor.wordHighlightBackground": "#afb8c133",
    "editor.wordHighlightStrongBackground": "#afb8c14d",
    "editor.findMatchBackground": "#fff8c5",
    "editor.findMatchHighlightBackground": "#fff8c580",
    "editor.findRangeHighlightBackground": "#fff8c54d",
    "editor.lineHighlightBackground": "#eaeef280",
    "editor.lineHighlightBorder": "#d0d7de",
    "editorWhitespace.foreground": "#d0d7de",
    "editorIndentGuide.background1": "#d8dee4",
    "editorIndentGuide.activeBackground1": "#afb8c1",
    "editorBracketMatch.background": "#dafbe1",
    "editorBracketMatch.border": "#116329",
    "editorBracketHighlight.foreground1": "#0550ae",
    "editorBracketHighlight.foreground2": "#953800",
    "editorBracketHighlight.foreground3": "#6639ba",
    "editorBracketHighlight.foreground4": "#116329",
    "editorBracketHighlight.foreground5": "#cf222e",
    "editorBracketHighlight.foreground6": "#0a3069",
    "editorGutter.background": "#ffffff",
    "editorGutter.modifiedBackground": "#9a6700",
    "editorGutter.addedBackground": "#1a7f37",
    "editorGutter.deletedBackground": "#cf222e",
    "editorOverviewRuler.border": "#ffffff",
    "editorOverviewRuler.findMatchForeground": "#9a6700",
    "editorOverviewRuler.errorForeground": "#cf222e",
    "editorOverviewRuler.warningForeground": "#9a6700",
    "editorOverviewRuler.infoForeground": "#0969da",
    "editorError.foreground": "#cf222e",
    "editorWarning.foreground": "#9a6700",
    "editorInfo.foreground": "#0969da",
    "editorHint.foreground": "#57606a",
    "editorWidget.background": "#f6f8fa",
    "editorWidget.foreground": "#1f2328",
    "editorWidget.border": "#d0d7de",
    "editorSuggestWidget.background": "#f6f8fa",
    "editorSuggestWidget.foreground": "#1f2328",
    "editorSuggestWidget.border": "#d0d7de",
    "editorSuggestWidget.highlightForeground": "#0969da",
    "editorSuggestWidget.selectedBackground": "#afb8c133",
    "editorHoverWidget.background": "#f6f8fa",
    "editorHoverWidget.foreground": "#1f2328",
    "editorHoverWidget.border": "#d0d7de",
    "peekView.border": "#d0d7de",
    "peekViewEditor.background": "#ffffff",
    "peekViewResult.background": "#f6f8fa",
    "peekViewResult.selectionBackground": "#afb8c133",
    "peekViewTitle.background": "#f6f8fa",
    "scrollbar.shadow": "#00000000",
    "scrollbarSlider.background": "#afb8c166",
    "scrollbarSlider.hoverBackground": "#8c959f66",
    "scrollbarSlider.activeBackground": "#8c959f99",
  },
};

export const NUMBER_OF_ALLOWED_MATCH_PARTICIPANTS = 2;
export const MAX_CONCEPTS_BEFORE_SHORTENING = 3;

export const SORT_BY_OPTIONS = ["most_recent", "oldest"] as const;
