packages:
  - "."

allowBuilds:
  esbuild: false
  msw: false
  sharp: false
  unrs-resolver: false

packageExtensions:
  "@hookform/resolvers@*":
    peerDependencies:
      zod: "^3.25 || ^4"
    peerDependenciesMeta:
      zod:
        optional: true
